export const API_ENPOINT = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  VERIFY_OTP: "/auth/verify-otp",
  RESEND_OTP: "/auth/resend-otp",
  FORGET_PASSWORD: "/auth/forget-password",
  CHANGE_PASSWORD: "/auth/change-password",
  RESET_PASSWORD: "/auth/reset-password",
  REFRESH_TOKEN: "/auth/refresh-token",
  MANAGE_ACCOUNT: "/manage-account/get-all-accounts",
  CHANGE_STATUS_ACCOUNT: "/manage-account/change-status-account",
  REGISTER_ACCOUNT: "/manage-account/register-account",
  GET_ALL_MATERIALS: "/material/get-all-materials",
  UPLOAD_MATERIAL: "/material/upload-material",
  DETAIL_MATERIAL: "/material",
  UPDATE_MATERIAL: "/material/update-material",
  CHANGE_STATUS_MATERIAL: "/material/change-status",
  DELETE_MATERIAL: "/material/delete",
  GET_ALL_KNOWLEDGE_STROE: "/knowledge-store/get-all",
  CREATE_KNOWLEDGE_STORE: "/knowledge-store/create",
  ADD_MATERIAL_TO_KNOWLEDGE_STORE: "/knowledge-store/add-materials",
  ASYNC_KNOWLEDGE_STORE: "/knowledge-store/async",
  LOGIN_GOOGLE: "/auth/login-with-google",
};
