export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/sign-up",
  FORGET_PASSWORD: "/forget-password",
  VERIFY_OTP: "/verify-otp",
  MANAGE_ACCOUNT: "/manage-account",
  MANAGE_MATERIALS: "/manage-materials",
  MANAGE_KNOWLEDGE_STORE: "/manage-knowledge-store",
  CHAT_BOT: "/chatbot",
  CHAT_BOT_ADMIN: "/chatbot-admin",
  RESET_PASSWORD: "/reset-password",
  OAUTH_SUCCESS: "/oauth-success",
  UPLOADED_MATERIAL: "/manage-user-material",
};
